name: Docker Hub

on:
  release:
    types:
      - published

jobs:
  publish:
    name: Publish Image
    runs-on: ubuntu-latest
    if: github.event.action == 'published'
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build Image
        run: docker build --tag ${{ secrets.DOCKER_IMAGE }} --build-arg CFPACK_VERSION ./docker
        env:
          CFPACK_VERSION: ${{ github.event.release.name }}
      - name: Verify Image
        run: test "$(docker run --rm ${{ secrets.DOCKER_IMAGE }} --version)" = "${{ github.event.release.name }}"
      - name: Tag Images
        run: |
          docker tag ${{ secrets.DOCKER_IMAGE }} ${{ secrets.DOCKER_IMAGE }}:${CFPACK_VERSION:0:1}
          docker tag ${{ secrets.DOCKER_IMAGE }} ${{ secrets.DOCKER_IMAGE }}:${CFPACK_VERSION}
        env:
          CFPACK_VERSION: ${{ github.event.release.name }}
      - name: Push Images
        run: |
          docker push ${{ secrets.DOCKER_IMAGE }}:latest
          docker push ${{ secrets.DOCKER_IMAGE }}:${CFPACK_VERSION:0:1}
          docker push ${{ secrets.DOCKER_IMAGE }}:${CFPACK_VERSION}
        env:
          CFPACK_VERSION: ${{ github.event.release.name }}
